/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Gaetan
 */
public class Puce extends javax.swing.JDialog  implements ActionListener{

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form Math
     */
    Editor ed;
    public Puce(Editor parent, boolean modal) {

        super(parent, modal);
        initComponents();
        ed = parent;
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });

        setLocationRelativeTo(null);

        tab[0] = new JButton("aucun(e)");
        tab[1] = new JButton("");
        tab[2] = new JButton("•");
        tab[3] = new JButton("o");
        tab[4] = new JButton("");
        tab[5] = new JButton("");
        tab[6] = new JButton("");
        tab[7] = new JButton("");
        tab[8] = new JButton("");
        tab[9] = new JButton("");     
        tab[10] = new JButton("");
        tab[11] = new JButton("");
       
        

        for(int i = 0; i<12; i++){
        tab[i].addActionListener(this);
        pan.add(tab[i]);
        }


    }
    JButton[] tab = new JButton[12];

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pan = new javax.swing.JPanel();
        annuler = new javax.swing.JButton();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pan.setLayout(new java.awt.GridLayout(3, 4, 5, 5));
        jTabbedPane1.addTab("Quelques puces proposé(e)s", pan);
        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(annuler))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(annuler)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {
        doClose(RET_CANCEL);
    }

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
    }

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify
    private javax.swing.JButton annuler;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pan;
    // End of variables declaration
    private int returnStatus = RET_CANCEL;


    public void actionPerformed(ActionEvent e) {
        if(e.getSource() == tab[0]){ ed.textPane.replaceSelection("");    ed.ppuce.setText(""); this.dispose();}
        if(e.getSource() == tab[1]){ ed.textPane.replaceSelection("        "); ed.ppuce.setText(""); this.dispose();}
        if(e.getSource() == tab[2]){ ed.textPane.replaceSelection("•        "); ed.ppuce.setText("•"); this.dispose();}
        if(e.getSource() == tab[3]){ ed.textPane.replaceSelection("o        "); ed.ppuce.setText("o"); this.dispose();}
        if(e.getSource() == tab[4]){ ed.textPane.replaceSelection("        "); ed.ppuce.setText(""); this.dispose();}
        if(e.getSource() == tab[5]){ ed.textPane.replaceSelection("        "); ed.ppuce.setText(""); this.dispose();}
        if(e.getSource() == tab[6]){ ed.textPane.replaceSelection("        "); ed.ppuce.setText(""); this.dispose();}
        if(e.getSource() == tab[7]){ ed.textPane.replaceSelection("        "); ed.ppuce.setText(""); this.dispose();}
        if(e.getSource() == tab[8]){ ed.textPane.replaceSelection("        "); ed.ppuce.setText(""); this.dispose();}
        if(e.getSource() == tab[9]){ ed.textPane.replaceSelection("        "); ed.ppuce.setText(""); this.dispose();}
        if(e.getSource() == tab[10]){ ed.textPane.replaceSelection("       "); ed.ppuce.setText(""); this.dispose();}
        if(e.getSource() == tab[11]){ ed.textPane.replaceSelection("       ");  ed.ppuce.setText("");this.dispose();}
       
    }
        


    }



